POST http://localhost:8080/courses
Content-Type: application/json

{
   "name": "SA",
   "code": "CS-535"
}

###

GET http://localhost:8080/courses

###

GET http://localhost:8080/courses/2

###

DELETE http://localhost:8080/courses/2

